# Generated by Django 4.2.9 on 2024-01-24 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market_Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusip', models.CharField(max_length=10)),
                ('trade_timestamp', models.DateTimeField(default=None)),
                ('trade_price', models.DecimalField(decimal_places=12, max_digits=20)),
            ],
        ),
    ]
