# Generated by Django 4.2.9 on 2024-01-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0002_market_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='trade_date',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='trade_time',
        ),
        migrations.AddField(
            model_name='trade',
            name='trade_timestamp',
            field=models.DateTimeField(default=None),
        ),
    ]
