# Generated by Django 4.2.9 on 2024-02-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analytics", "0006_alter_uploads_user_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="Trade",
            name="trade_price",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="Market_Prices",
            name="trade_price",
            field=models.FloatField(),
        ),
    ]
