# Generated by Django 4.2.9 on 2024-09-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analytics", "0009_uploadhoodwinked_platform"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadBlockhouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.CharField(max_length=255)),
                ("account_type", models.CharField(max_length=255)),
                ("file_name", models.CharField(max_length=255)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("file_size", models.IntegerField()),
                ("file_path", models.CharField(max_length=500)),
            ],
        ),
    ]
