# Generated by Django 4.2.9 on 2024-09-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analytics", "0010_uploadblockhouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadblockhouse",
            name="platform",
            field=models.CharField(default="unknown", max_length=255),
        ),
    ]
