import os
import time
from datetime import datetime, timedelta
import pytz

import pandas as pd
import numpy as np
import torch

import warnings


from blockhouse_mls.equities.sell.utils.macro_model import MetaLearner
from blockhouse_mls.equities.sell.utils.data_handler import DataProcessor, InferenceDataHandler
from blockhouse_mls.equities.sell.utils.macro_model_utils import MacroTraderModel
from blockhouse_mls.equities.utils.fetch_merge_data import PolygonClient
from blockhouse_mls.equities.sell.utils.env import TradingEnvironment, CustomTradingEnvironment, TradingEnvironmentMicro
from blockhouse_mls.equities.sell.utils.micro_model_utils import MicroTraderModel

os.environ['KMP_DUPLICATE_LIB_OK'] = 'TRUE'
os.environ['OMP_NUM_THREADS'] = '1'
'''
Because of this error:
 [error] Disposing session as kernel process died ExitCode: 3, Reason: OMP: Error #15: Initializing libiomp5md.dll, but found libomp140.x86_64.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
'''

warnings.filterwarnings("ignore")


class EquitiesSellInference:

    def __init__(self, macro_model_dir = 'Models', micro_model_dir = 'MicroModels', data_dir = 'Data'): 
        ## Initialize the variables
        # Initialize the model directory, where the models will be saved
        self.MACRO_MODEL_DIR = macro_model_dir
        os.makedirs(self.MACRO_MODEL_DIR, exist_ok=True)

        self.MICRO_MODEL_DIR = micro_model_dir
        os.makedirs(self.MICRO_MODEL_DIR, exist_ok=True)


        # Initialize the data directory, where the data will be stored
        self.data_dir = data_dir
        os.makedirs(self.data_dir, exist_ok=True)

        # Initialize the MacroTraderModel
        self.macro_trader = MacroTraderModel(self.MACRO_MODEL_DIR)

        # Initialize the MicroTraderModel
        self.micro_trader = MicroTraderModel(self.MICRO_MODEL_DIR)

        # Initialize the data processor
        self.data_processor = DataProcessor()

        # Inference data handler
        self.inference_data_handler = InferenceDataHandler()

        # Initialize the MetaLearner
        self.meta = MetaLearner()

        self.data_client = PolygonClient(self.data_dir)


    def get_schedule(self, timeframe, transaction_size, market_cap_int, input_row, data):
        """
        Generates a trading schedule based on the transaction size and input data.

        Args:
        - timeframe (int): The timeframe for trade execution.
        - transaction_size (int): The size of the transaction.
        - input_row (pd.DataFrame): The input data row with forecasts and technical indicators.

        Returns:
        - list: A list of trades executed based on the generated schedule.
        """
        print("LOGGING: Generating Schedule...")
        trades, micro_input = self.macro_trader.infer_macro(timeframe, transaction_size, market_cap_int,  input_row, data, meta=self.meta, inference_data_handler=self.inference_data_handler)
        return trades, micro_input

    def run_pipeline(self, ticker, start_timestamp = (datetime.now(pytz.UTC) - timedelta(days=2)).strftime('%Y-%m-%d'), end_timestamp=datetime.now(pytz.UTC).strftime('%Y-%m-%d'), timeframe=390, inventory=10000, trade_set_counter=1):
        """
        Runs the entire pipeline for the trading model, including data retrieval, 
        technical indicator addition, forecasting, and generating trade schedules.

        Returns:
        - list: The list of trades generated by the model.
        """
        start_time = time.time()
        # Create the trading environment
        data = self.data_client.fetch_and_merge_data(ticker,start_date=start_timestamp,end_date=end_timestamp)
        data = self.data_processor.add_technical_indicators(data)

        input_row = self.inference_data_handler.add_forecasts(data)
        market_cap_int = self.data_client.get_market_cap(ticker)
        trades, micro_input = self.get_schedule(timeframe, inventory, market_cap_int, input_row, data)
        micro_input['Timestamp'] = trades['timestamp'].tolist()
        # Display the column names of the trades DataFrame
        # print(micro_input)
        # macro_timestamps = trades['timestamp'].tolist()
        micro_input['Ticker'] = [ticker]*len(micro_input)
        micro_input['Inventory'] = [inventory]*len(micro_input)
        micro_input['Trade_Set_ID'] = [f"set_{trade_set_counter}"]*len(micro_input)


        # ## run micro trader
        micro_env = TradingEnvironmentMicro(micro_input, preferred_timeframe=timeframe, initial_inventory=inventory)
        micro_model = self.micro_trader.load_model(micro_env, {}) 
    
        # Reset the environment to start inference
        obs = micro_env.reset()

        # Initialize an empty list to store trade details
        trade_details = []

        for _ in range(len(micro_input)):
            # Predict the action to take based on the current observation
            action, _states = micro_model.predict(obs)
            
            # Step through the micro_environment using the predicted action
            obs, rewards, done, info = micro_env.step(action)
            
            # If the micro_environment is done, break the loop
            if done:
                break
        trade_details = micro_env.results
        # Render the final state of the micro_environment
        micro_env.render()
        
        return trade_details

