# Generated by Django 4.2.9 on 2024-01-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusip', models.CharField(max_length=10)),
                ('trade_date', models.DateField()),
                ('trade_time', models.TimeField()),
                ('trade_size', models.IntegerField()),
                ('face_value', models.IntegerField()),
                ('asset_inventory', models.IntegerField()),
                ('fill', models.IntegerField()),
                ('execution_time', models.IntegerField()),
                ('trade_price', models.DecimalField(decimal_places=12, max_digits=20)),
                ('trade_direction', models.CharField(max_length=4)),
                ('counterparty', models.CharField(max_length=50)),
                ('trader', models.CharField(max_length=50)),
            ],
        ),
    ]
