# -*- coding: utf-8 -*-
"""Total_Features.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JnzrmTaIxPQ4Cl5hiSR2gQsFg0nNP-t_
"""

import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import ruptures as rpt
from statsmodels.tsa.stattools import adfuller
from sklearn.neighbors import NearestNeighbors
import os
from scipy.stats import entropy

# Fetch data from Yahoo Finance
def fetch_data(ticker_symbol, start_date, end_date):
    stock_data = yf.download(ticker_symbol, start=start_date, end=end_date)
    stock_data['Log Stock Price'] = np.log(stock_data['Adj Close'])
    stock_data['Log Returns'] = stock_data['Log Stock Price'].diff()
    return stock_data

# Apply CUSUM to detect structural breaks
def apply_cusum(stock_data, threshold=0.03):
    mean_value = stock_data['log_returns'].mean()
    cumulative_sum = 0
    cusum_signal = []
    for price in stock_data['log_returns'].dropna():
        cumulative_sum += price - mean_value
        if abs(cumulative_sum) > threshold:
            cusum_signal.append(1)
            cumulative_sum = 0  # Reset signal
        else:
            cusum_signal.append(0)
    stock_data['cusum_feature'] = pd.Series(cusum_signal, index=stock_data['log_returns'].dropna().index)
    stock_data['cusum_feature'] = stock_data['cusum_feature'].reindex(stock_data.index, fill_value=0)
    return stock_data

# Detect structural breaks using Ruptures
def detect_breakpoints(stock_data, model="l2", pen=1):
    algo = rpt.Pelt(model=model).fit(stock_data['log_stock_price'].dropna().values)
    breakpoints = algo.predict(pen=pen)
    breakpoints = stock_data.index[breakpoints[:-1]]  # Ensure index bounds
    stock_data['structural_break'] = 0
    stock_data.loc[breakpoints, 'structural_break'] = 1

    plt.figure(figsize=(10, 6))
    plt.plot(stock_data['log_stock_price'], label="log_stock_price")
    for bp in breakpoints:
        plt.axvline(x=bp, color='red', linestyle='--', label='Break Point')
    plt.show()

    return stock_data

# Rolling SADF feature
def rolling_sadf(stock_data, window=60):
    sadf_values = []
    for i in range(len(stock_data['log_stock_price'].dropna()) - window + 1):
        sub_series = stock_data['log_stock_price'].dropna().iloc[i:i + window]
        result = adfuller(sub_series)
        sadf_values.append(result[0])
    sadf_values = [np.nan] * (window - 1) + sadf_values
    stock_data['SADF Feature'] = pd.Series(sadf_values, index=stock_data['log_stock_price'].dropna().index)
    return stock_data

# Lorentzian Classifier
def apply_lorentzian_classifier(stock_data, feature_columns, neighbors_count=8):
    X = stock_data[feature_columns].dropna().values
    stock_data_cleaned = stock_data.dropna(subset=feature_columns).copy()

    nbrs = NearestNeighbors(n_neighbors=neighbors_count, metric=lorentzian_distance)
    nbrs.fit(X)
    distances, indices = nbrs.kneighbors(X)

    prediction = np.sign(np.diff(stock_data_cleaned['Close'].values, prepend=np.nan))
    stock_data_cleaned['Prediction'] = prediction
    stock_data_cleaned['ANN_Prediction'] = np.nan

    for i in range(len(stock_data_cleaned)):
        neighbor_indices = indices[i]
        neighbor_votes = [stock_data_cleaned.iloc[idx]['Prediction'] for idx in neighbor_indices if idx < len(stock_data_cleaned)]
        if not neighbor_votes:
            continue
        stock_data_cleaned.iloc[i, stock_data_cleaned.columns.get_loc('ANN_Prediction')] = pd.Series(neighbor_votes).mode()[0]

    stock_data.loc[stock_data_cleaned.index, 'Prediction'] = stock_data_cleaned['Prediction']
    stock_data.loc[stock_data_cleaned.index, 'ANN_Prediction'] = stock_data_cleaned['ANN_Prediction']

    return stock_data

# Helper function for Lorentzian distance
def lorentzian_distance(x, y):
    return np.sum(np.log(1 + np.abs(x - y)))

# Corwin-Schultz Spread Estimator
def corwin_schultz(stock_data, sl=1):
    def get_beta(series, sl):
        hl = np.log(series['high'] / series['low']) ** 2
        beta = hl.rolling(window=2).sum().rolling(window=sl).mean()
        return beta.dropna()

    def get_gamma(series):
        h2 = series['high'].rolling(window=2).max()
        l2 = series['low'].rolling(window=2).min()
        gamma = np.log(h2 / l2) ** 2
        return gamma.dropna()

    def get_alpha(beta, gamma):
        den = 3 - 2 * 2 ** 0.5
        alpha = (2 ** 0.5 - 1) * (beta ** 0.5) / den
        alpha = -(gamma / den) ** 0.5
        return alpha.dropna()

    beta = get_beta(stock_data, sl)
    gamma = get_gamma(stock_data)
    alpha = get_alpha(beta, gamma)
    spread = 2 * (np.exp(alpha) - 1) / (1 + np.exp(alpha))
    stock_data['corwin_schultz_spread'] = spread
    return stock_data

# Plot VPIN (Volume-Synchronized Probability of Informed Trading)
def plot_vpin(vpin_series):
    plt.figure(figsize=(10, 6))
    plt.plot(vpin_series.index, vpin_series.values, label='VPIN', color='blue', linewidth=2)
    plt.title('VPIN (Volume-Synchronized Probability of Informed Trading)')
    plt.xlabel('Cumulative Volume Bars')
    plt.ylabel('VPIN Value')
    plt.grid(True)
    plt.legend()
    plt.show()

# Calculate VPIN feature
def compute_vpin(volume_bars, window):
    order_imbalance = np.abs(volume_bars['trade_sign'])  # Absolute imbalance
    total_volume = volume_bars['volume']
    vpin = order_imbalance.rolling(window).mean() / total_volume.rolling(window).mean()
    return vpin

# Classify trades using adjusted Close or Close instead of Bid/Ask
def classify_trades(stock_data):
    mid_price = stock_data['close']  # Use 'Adj Close' as a proxy for mid-price
    price_diff = mid_price.diff()
    trade_sign = np.sign(price_diff).fillna(0)
    trade_sign[trade_sign == 0] = trade_sign.shift(1)  # Carry forward the last trade sign if no change
    stock_data['trade_sign'] = trade_sign
    return stock_data

# Get volume bars
def get_volume_bars(stock_data, volume_threshold):
    stock_data['cum_volume'] = stock_data['volume'].cumsum()
    bar_index = np.floor(stock_data['cum_volume'] / volume_threshold)
    stock_data['bar_index'] = bar_index
    volume_bars = stock_data.groupby(bar_index).agg({
        'volume': 'sum',
        'log_returns': 'sum',
        'log_stock_price': 'last',
        'trade_sign': 'sum'
    })
    return volume_bars

# Rolling volatility in 20 days window
def calculate_rolling_volatility(stock_data, window_size=20):
    stock_data['mid_price'] = (stock_data['high'] + stock_data['low']) / 2  # Calculate mid-price using High and Low
    stock_data['Rolling Volatility'] = stock_data['mid_price'].rolling(window=window_size).std()  # Rolling standard deviation
    return stock_data

# Big event indicators as indicator function 0 or 1
def big_event_indicator(stock_data, event_dates):
    """
    Add a binary indicator (0 or 1) for the occurrence of a big event.

    Parameters:
    - stock_data (pd.DataFrame): The stock data.
    - event_dates (list of str): List of event dates in 'YYYY-MM-DD' format.
    """
    big_event_indicator = np.zeros(len(stock_data))
    for event_date in event_dates:
        event_date = pd.Timestamp(event_date)  # Convert to pd.Timestamp
        big_event_indicator[(stock_data.index >= event_date) & (stock_data.index < event_date + pd.Timedelta(hours=1))] = 1
    stock_data['Big Event Indicator'] = pd.Series(big_event_indicator, index=stock_data.index)
    return stock_data

# Fibonacci Retracement Levels
def apply_fibonacci_alpha_factors(stock_data):
    period_high = stock_data['high'].rolling(window=365, min_periods=1).max()
    period_low = stock_data['low'].rolling(window=365, min_periods=1).min()

    for level in [0.236, 0.382, 0.5, 0.618, 0.786]:
        stock_data[f'fib_level_{level}'] = period_high - (period_high - period_low) * level

    return stock_data

# Main function integrating Fibonacci features and new volatility/event indicators
def main_test():
    ticker = "AAPL"
    start_date = "2024-09-01"
    end_date = "2024-10-02"

    # Fetch and process data
    stock_data = fetch_data(ticker, start_date, end_date)

    # Apply new features
    stock_data = calculate_rolling_volatility(stock_data, window_size=20)
    event_dates = ['2018-12-24', '2020-03-16']  # Example big event dates
    stock_data = big_event_indicator(stock_data, event_dates)

    # Apply existing features
    stock_data = apply_cusum(stock_data)
    stock_data = detect_breakpoints(stock_data)
    stock_data = rolling_sadf(stock_data)
    stock_data = corwin_schultz(stock_data)
    stock_data = classify_trades(stock_data)
    stock_data = apply_fibonacci_alpha_factors(stock_data)

    # Get volume bars and compute VPIN
    volume_bars = get_volume_bars(stock_data, volume_threshold=100000000)
    vpin_series = compute_vpin(volume_bars, window=2)
    plot_vpin(vpin_series)

    # Print the final DataFrame with new features
    print(stock_data.head())

def main_pipeline(stock_data):

    stock_data['log_stock_price'] = np.log(stock_data['close'])
    stock_data['log_returns'] = stock_data['log_stock_price'].diff()

    stock_data = calculate_rolling_volatility(stock_data, window_size=20)
    # Apply existing features
    stock_data = apply_cusum(stock_data)
    # stock_data = detect_breakpoints(stock_data)
    stock_data = rolling_sadf(stock_data)
    stock_data = corwin_schultz(stock_data)
    stock_data = classify_trades(stock_data)
    stock_data = apply_fibonacci_alpha_factors(stock_data)

    # Get volume bars and compute VPIN
    volume_bars = get_volume_bars(stock_data, volume_threshold=100000000)
    vpin_series = compute_vpin(volume_bars, window=2)
    volume_bars['bar_index'] = volume_bars.index
    volume_bars.reset_index(inplace=True)
    volume_bars.drop(columns = ["cum_volume", "volume"], inplace = True)
    volume_bars['vpin_series'] = vpin_series.values
    merged_stock_data = pd.merge(stock_data, volume_bars, how='left', on=['bar_index'])
    print('first processing done')
    return merged_stock_data
    # event_dates = ['2018-12-24', '2020-03-16']  # Example big event dates
    # stock_data = big_event_indicator(stock_data, event_dates)



if __name__ == "__main__":
    pass