from django.urls import path, re_path

from . import views

urlpatterns = [
    re_path(r'^bargraph/?$', views.barchart),
    re_path(r'bid_ask_chart/?$', views.bid_ask_chart),
    re_path(r'^delete_file/?$', views.delete_file),
    re_path(r'^delete_file/hoodwinked/?$', views.hoodwinked_delete_file),
    re_path(r'^delete_file/blockhouse/?$', views.blockhouse_delete_file),
    re_path(r'^execution_over_time/?$', views.executions_over_time),
    re_path(r'^files/blockhouse?$', views.files_list),
    re_path(r'^files/hoodwinked/?$', views.hoodwinked_files_list),
    re_path(r'^hoodwinked_analyze/?$', views.hoodwinked_analyze),
    re_path(r'^blockhouse_analyze/?$', views.blockhouse_analyze),
    re_path(r'^hoodwinked_analyze_plaid/?$', views.hoodwinked_analyze_plaid),
    re_path(r'^hoodwinked_graph/?$', views.hoodwinked_graph),
    re_path(r'^hoodwinked_graph_plaid/?$', views.hoodwinked_graph_plaid),
    re_path(r'^hoodwinked_get_metrics/?$', views.hoodwinked_get_initial_metrics),
    re_path(r'^upload_plaid_to_s3/?$', views.plaid_data_to_csv),
    re_path(r'^get_recommendations/?$', views.process_pipeline_for_ticker),
    re_path(r'^get_buy_recommendations/?$', views.process_pipeline_for_ticker_buy),
    re_path(r'^heatmap/?$', views.heatmap),
    re_path(r'^piechart/?$', views.piechart),
    re_path(r'^signup/?$', views.signup),
    re_path(r'^signin/?$', views.signin),
    re_path(r'^signin/referral?$', views.get_referral_link),
    re_path(r'^signup/update-referral-status?$', views.update_referral),
    re_path(r'^signup/update-referral-clicks?$', views.update_referral_clicks),
    re_path(r'^signin/reward', views.calculate_rewards),
    re_path(r'^email_capture/?$', views.email_capture),
    re_path(r'^traded_quantities/?$', views.traded_quantities),
    re_path(r'^upload/?$', views.upload_file),
    re_path(r'^upload/hoodwinked?$', views.hoodwinked_upload_file),
    re_path(r"^upload/blockhouse?$", views.blockhouse_upload_file),
    re_path(r'^generate-report/hoodwinked?$', views.hoodwinked_generate_report),
    re_path(r'^generate-report/hoodwinked_plaid?$', views.hoodwinked_generate_report_plaid),
    re_path(r'^generate-report/hoodwinked_onboard_data?$', views.hoodwinked_onboard_plaid_data),
    re_path(r'^chart-calculation?$', views.chartCalculation),
    re_path(r'^chat/?$', views.chat),
    re_path(r'^chat/check_messages/?$', views.check_messages),
    re_path(r'^chat/send_chat_message/?$', views.send_chat_message),
]
