# Generated by Django 4.2.9 on 2024-01-24 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Analytics', '0003_remove_trade_trade_date_remove_trade_trade_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market_prices',
            name='trade_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trade_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
