# Generated by Django 4.2.9 on 2024-07-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analytics", "0007_auto_20240225_2025"),
    ]

    operations = [
        migrations.CreateModel(
            name="UploadHoodWinked",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_email", models.CharField(max_length=255)),
                ("file_name", models.CharField(max_length=255)),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
                ("file_size", models.IntegerField()),
                ("file_path", models.CharField(max_length=500)),
            ],
        ),
    ]
