# Generated by Django 4.2.9 on 2024-07-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Analytics", "0008_uploadhoodwinked"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadhoodwinked",
            name="platform",
            field=models.CharField(default="exit", max_length=255),
            preserve_default=False,
        ),
    ]
